model : 'simple-baselines-pose'
dataset_name : 'tmp-mpii-keypoints'
input_size: [256, 192] # [height, width] 4:3 ratio
output_size: [64, 48] # [height, width]
in_channels: 3
num_keypoints : 16
sigma: 2 # 2D Gaussian Filter, size = 6*sigma + 3
class_labels : [
  'r_ankle', 
  'r_knee', 
  'r_hip', 
  'l_hip', 
  'l_knee', 
  'l_ankle', 
  'pelvis', 
  'thorax', 
  'upper_neck', 
  'head_top', 
  'r_wrist', 
  'r_elbow', 
  'r_shoulder',
  'l_shoulder', 
  'l_elbow',
  'l_wrist'
]

# epochs: 365
epochs: 500

# train_path : '/home/fssv2/myungsang/datasets/mpii_human_pose/annotations/train.json'
# val_path : '/home/fssv2/myungsang/datasets/mpii_human_pose/annotations/valid.json'
# train_path : '/home/fssv2/myungsang/datasets/mpii_human_pose/annotations/tmp_train.json'
# val_path : '/home/fssv2/myungsang/datasets/mpii_human_pose/annotations/tmp_valid.json'
train_path : '/home/fssv2/myungsang/datasets/mpii_human_pose/annotations/tmp.json'
val_path : '/home/fssv2/myungsang/datasets/mpii_human_pose/annotations/tmp.json'
img_dir : '/home/fssv2/myungsang/datasets/mpii_human_pose/images'
workers: 0 # number of workers to generate data
batch_size: 1

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0
  log_every_n_steps: 2

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [1] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

# optimizer: 'adam'
# optimizer_options:
#   lr: 1e-3
#   weight_decay: 5e-4

# optimizer: 'radam'
# optimizer_options:
#   lr: 1e-3
#   weight_decay: 1e-5

# optimizer: 'adamw'
# optimizer_options:
#   lr: 1e-3
#   weight_decay: 5e-4

# optimizer: 'rmsprop'
# optimizer_options:
#   lr: 1e-3
#   momentum: 0.9
#   weight_decay: 5e-4
  # eps: 0.0316
  # alpha: 0.9

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  momentum: 0.9
  weight_decay: 5e-4
  nesterov: True

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [700, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 1100
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 220
#   gamma: 0.96

scheduler: 'yolo_lr'
scheduler_options:
  burn_in: 5
  steps: [200, 400]
  scales: [0.1, 0.1]
