model : 'spm'
backbone: 'darknet19'
dataset_name : 'mpii-keypoints'
input_size: 512
output_size: 256
in_channels: 3
num_keypoints : 16
sigma: 2 # 2D Gaussian Filter, size = 6*sigma + 3
class_labels : [
  'r_ankle', 
  'r_knee', 
  'r_hip', 
  'l_hip', 
  'l_knee', 
  'l_ankle', 
  'pelvis', 
  'thorax', 
  'upper_neck', 
  'head_top', 
  'r_wrist', 
  'r_elbow', 
  'r_shoulder',
  'l_shoulder', 
  'l_elbow',
  'l_wrist'
]

epochs: 365

train_path : '/home/fssv2/myungsang/datasets/mpii_human_pose/annotations/train.json'
val_path : '/home/fssv2/myungsang/datasets/mpii_human_pose/annotations/valid.json'
img_dir : '/home/fssv2/myungsang/datasets/mpii_human_pose/images'
workers: 32 # number of workers to generate data
batch_size: 64

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [0] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

# optimizer: 'adam'
# optimizer_options:
#   lr: 0
#   weight_decay: 1e-5

# optimizer: 'radam'
# optimizer_options:
#   lr: 1e-3
#   weight_decay: 1e-5

# optimizer: 'adamw'
# optimizer_options:
#   lr: 0
#   weight_decay: 1e-5

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  momentum: 0.9
  weight_decay: 5e-4

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [700, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 1100
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 220
#   gamma: 0.96

scheduler: 'yolo_lr'
scheduler_options:
  burn_in: 1000
  steps: [40000, 60000]
  scales: [0.1, 0.1]
