model : 'single-stage-pose-machines'
backbone: 'darknet19'
backbone_pretrained: '' # 'tiny-imagenet' or '' 
dataset_name : 'coco-keypoints'
input_size: 512
output_size: 128
in_channels: 3
num_keypoints : 17
sigma: 2 # 2D Gaussian Filter, size = 6*sigma + 3
class_labels : [
  'nose', 
  'left_eye', 
  'right_eye', 
  'left_ear', 
  'right_ear', 
  'left_shoulder', 
  'right_shoulder', 
  'left_elbow', 
  'right_elbow',
  'left_wrist', 
  'right_wrist', 
  'left_hip',
  'right_hip', 
  'left_knee',
  'right_knee',
  'left_ankle',
  'right_ankle'
]
conf_threshold: 0.25

epochs: 365

# train_path : '/home/fssv2/myungsang/datasets/coco_2017/annotations/person_keypoints_train2017.json'
# val_path : '/home/fssv2/myungsang/datasets/coco_2017/annotations/person_keypoints_val2017.json'
# img_dir : '/home/fssv2/myungsang/datasets/coco_2017'
train_path : '/home/fssv2/myungsang/datasets/coco_2017/tiny_coco_keypoints/annotations/person_keypoints_train2017.json'
val_path : '/home/fssv2/myungsang/datasets/coco_2017/tiny_coco_keypoints/annotations/person_keypoints_val2017.json'
img_dir : '/home/fssv2/myungsang/datasets/coco_2017/tiny_coco_keypoints'
workers: 32 # number of workers to generate data
batch_size: 32

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0
  # log_every_n_steps: 3

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [0] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  momentum: 0.9
  weight_decay: 5e-3
  nesterov: True

scheduler: 'yolo_lr'
scheduler_options:
  burn_in: 9000
  steps: [350000]
  scales: [0.1]

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [700, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 1100
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 220
#   gamma: 0.96

# experimental_options:
#   os: 'windows' # add this option if an error about NCCL occurs in windows
#   callbacks:
#     - 'SWA'